create table "public"."seeds" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);

alter table "public"."seeds" enable row level security;

CREATE UNIQUE INDEX seeds_pkey ON public.seeds USING btree (id);

alter table "public"."seeds" add constraint "seeds_pkey" PRIMARY KEY using index "seeds_pkey";