create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "email" text not null,
    "password" text,
    "roles_id" bigint not null,
    "countries_id" bigint not null,
    "created_at" timestamp with time zone default now()
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."users" add constraint "users_countries_id_fkey" FOREIGN KEY (countries_id) REFERENCES countries(id) not valid;

alter table "public"."users" validate constraint "users_countries_id_fkey";

alter table "public"."users" add constraint "users_roles_id_fkey" FOREIGN KEY (roles_id) REFERENCES roles(id) not valid;

alter table "public"."users" validate constraint "users_roles_id_fkey";