create table "public"."countries" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "code" character varying not null
);


alter table "public"."countries" enable row level security;

CREATE UNIQUE INDEX countries_pkey ON public.countries USING btree (id);

alter table "public"."countries" add constraint "countries_pkey" PRIMARY KEY using index "countries_pkey";
