create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text not null,
    "score" integer not null,
    "price" numeric not null,
    "tasting_sheet" text not null,
    "originators_id" bigint,
    "seeds_id" bigint,
    "token_id" text,
    "created_at" timestamp with time zone default now(),
    "deleted_it" timestamp with time zone
);

alter table "public"."products" enable row level security;

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."products" add constraint "products_originators_id_fkey" FOREIGN KEY (originators_id) REFERENCES originators(id) not valid;

alter table "public"."products" validate constraint "products_originators_id_fkey";

alter table "public"."products" add constraint "products_seeds_id_fkey" FOREIGN KEY (seeds_id) REFERENCES seeds(id) not valid;

alter table "public"."products" validate constraint "products_seeds_id_fkey";